name: PullRequest Workflow
on:
  pull_request:
    branches: [main]
jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Node.js setup
        uses: actions/setup-node@v2
        with:
          node-version: '20.9.0' 
      - name: Install dependencies
        run: npm install
      - name: Checking completion of workflow
        run: ec

