name: Temp
on:
  pull_request:
    branches: [main]
jobs:
  test-packer:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Cloud Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.SA_KEY}}'
      - name: Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: gcloud CLI
        run: gcloud info
      - name: Image name
        run: echo "csye6225-1712767964" > imagename.txt  
      - name: Setting Variables for Template
        run: |
          echo "db_host=$(echo $(gcloud secrets versions access latest --secret='secret-host'))" >> $GITHUB_ENV
          echo "db_pass=$(echo $(gcloud secrets versions access latest --secret='secret-pass'))" >> $GITHUB_ENV
          echo "image_name=$(cat imagename.txt)" >> $GITHUB_ENV
          echo "template_name=centos-vm-template-$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
      - name: Echo Names
        run: |
          echo $template_name
          echo $image_name
      - name: New VM Template
        run: |
          gcloud compute instance-templates create $template_name \
            --instance-template-region=us-central1  \
            --region=us-central1 \
            --machine-type=e2-standard-2 \
            --image=$image_name \
            --subnet=webapp \
            --service-account=${{ secrets.VM_SA }} \
            --scopes=https://www.googleapis.com/auth/cloud-platform \
            --metadata=db-user=webapp,db-name=mydb,db-host=$db_host,db-pass=$db_pass,startup-script="${{ secrets.STARTUP_SCRIPT }}" \
            --boot-disk-type=pd-standard
      - name: Completion Status
        run: echo "DONE!"    
