name: PullRequest Workflow
on:
  pull_request:
    branches: [main]
jobs:
  integration-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{ secrets.PSQL_DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.PSQL_DB_PASS }}
        ports:
          - 8080:8080

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Node.js setup
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npx jest
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 8080
      - name: Checking completion of workflow
        run: echo "DONE!"
