name: PullRequest Workflow
on:
  pull_request:
    branches: [main]
jobs:
  integration-tests:
    runs-on: ubuntu-latest


    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Node.js setup
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - uses: ikalnytskyi/action-setup-postgres@v5
        with:
          username: ${{ secrets.PSQL_DB_USER }}
          password: ${{ secrets.PSQL_DB_PASS }}
          database: mydb
          port: 8080
        id: postgres
      - name: Start postgres
        run: systemctl start postgresql  
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npx jest
        env:
          PSQL_DB_USER: ${{ secrets.PSQL_DB_USER }}
          PSQL_DB_PASS: ${{ secrets.PSQL_DB_PASS }}
          PSQL_DB: mydb
          POSTGRES_HOST: localhost
          PORT: 8080

      - name: Checking completion of workflow
        run: echo "DONE!"
